executor: go-machine
steps:
  - setup-go
  - checkout
  - restore_go_mod_cache
  - attach_workspace:
      at: .
  - run:
      name: Build dev binary
      command: |
        # Move dev UI assets to expected location
        rm -rf ./pkg
        mkdir ./pkg

        # Build dev binary
        make ci-bootstrap
        make prep
        mkdir -p bin/linux/amd64
        go build -v -tags vault -o bin/linux/amd64/vault
  - persist_to_workspace:
      root: .
      paths:
        - bin
