version: "2.1"
executors:
  builder:
    docker:
      - image: docker.mirror.hashicorp.services/circleci/buildpack-deps
    shell: /usr/bin/env bash -euo pipefail -c
    environment:
      AUTO_INSTALL_TOOLS: "YES"
      BUILDKIT_PROGRESS: plain
      PRODUCT_REVISION: 33e6919abdc2300f4f3f712015a910d47c0c1f6d
  builder-machine:
    resource_class: xlarge
    machine:
      image: ubuntu-1604:202007-01
    shell: /usr/bin/env bash -euo pipefail -c
    environment:
      AUTO_INSTALL_TOOLS: "YES"
      BUILDKIT_PROGRESS: plain
      PRODUCT_REVISION: 33e6919abdc2300f4f3f712015a910d47c0c1f6d
jobs:
  build-common-layers:
    executor: builder-machine
    steps:
      - add_ssh_keys:
          fingerprints:
            - c6:96:98:82:dc:04:6c:39:dd:ac:83:05:e3:15:1c:98
      - checkout:
          path: .
      - run:
          command: make -C packages*.lock write-builder-cache-keys
          name: Write builder layer cache keys
      - restore_cache:
          key: build-ui_90fd_{{checksum ".buildcache/cache-keys/build-ui-90fdcda527d1cfee8060beabb684c580d036ee74"}}
          keys:
            - ui-dependencies_03a9_{{checksum ".buildcache/cache-keys/ui-dependencies-03a9560cf6f4a4b3fbfbb962620287b558dbf506"}}
            - install-yarn_4a71_{{checksum ".buildcache/cache-keys/install-yarn-4a71e9de991f85332680d0309a9fd3eef4d33a2c"}}
            - set-workdir_3f6f_{{checksum ".buildcache/cache-keys/set-workdir-3f6fd622b823df140b6d5bb7d1078de649239243"}}
            - install-go-tools_8ddd_{{checksum ".buildcache/cache-keys/install-go-tools-8dddb408568872d9ec907a8ba53068b13908ad64"}}
            - install-go_aada_{{checksum ".buildcache/cache-keys/install-go-aadaf7c6eb9ff4cceff9ba27d6e0253fb5bbec24"}}
            - base_c6cd_{{checksum ".buildcache/cache-keys/base-c6cdf1b224722d2520e082320f2a71875913247c"}}
          name: 'Restore Layer Cache: build-ui'
      - run:
          command: LAYER_SPEC_ID=06-build-ui-90fdcda527d1cfee8060beabb684c580d036ee74 make -C packages*.lock load-builder-cache
          name: Load whatever builder cache we have (if any) into the Docker daemon
      - run:
          command: |2-

            KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
            eval "$(ssh-agent -s)"
            if [ -f "$KEYFILE" ]; then
              ssh-add "$KEYFILE"
            else
              echo "==> INFO: SSH key for github.com not found"
              echo "    Attempts to access private repositories from within"
              echo "    the build will fail, e.g. for private go modules, or"
              echo "    attempts to directly clone private repositories."
            fi

            make -f packages*.lock/layer.mk 00-base-c6cdf1b224722d2520e082320f2a71875913247c-image
          name: Build base layer
      - run:
          command: |2-

            KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
            eval "$(ssh-agent -s)"
            if [ -f "$KEYFILE" ]; then
              ssh-add "$KEYFILE"
            else
              echo "==> INFO: SSH key for github.com not found"
              echo "    Attempts to access private repositories from within"
              echo "    the build will fail, e.g. for private go modules, or"
              echo "    attempts to directly clone private repositories."
            fi

            make -f packages*.lock/layer.mk 01-install-go-aadaf7c6eb9ff4cceff9ba27d6e0253fb5bbec24-image
          name: Build install-go layer
      - run:
          command: |2-

            KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
            eval "$(ssh-agent -s)"
            if [ -f "$KEYFILE" ]; then
              ssh-add "$KEYFILE"
            else
              echo "==> INFO: SSH key for github.com not found"
              echo "    Attempts to access private repositories from within"
              echo "    the build will fail, e.g. for private go modules, or"
              echo "    attempts to directly clone private repositories."
            fi

            make -f packages*.lock/layer.mk 02-install-go-tools-8dddb408568872d9ec907a8ba53068b13908ad64-image
          name: Build install-go-tools layer
      - run:
          command: |2-

            KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
            eval "$(ssh-agent -s)"
            if [ -f "$KEYFILE" ]; then
              ssh-add "$KEYFILE"
            else
              echo "==> INFO: SSH key for github.com not found"
              echo "    Attempts to access private repositories from within"
              echo "    the build will fail, e.g. for private go modules, or"
              echo "    attempts to directly clone private repositories."
            fi

            make -f packages*.lock/layer.mk 03-set-workdir-3f6fd622b823df140b6d5bb7d1078de649239243-image
          name: Build set-workdir layer
      - run:
          command: |2-

            KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
            eval "$(ssh-agent -s)"
            if [ -f "$KEYFILE" ]; then
              ssh-add "$KEYFILE"
            else
              echo "==> INFO: SSH key for github.com not found"
              echo "    Attempts to access private repositories from within"
              echo "    the build will fail, e.g. for private go modules, or"
              echo "    attempts to directly clone private repositories."
            fi

            make -f packages*.lock/layer.mk 04-install-yarn-4a71e9de991f85332680d0309a9fd3eef4d33a2c-image
          name: Build install-yarn layer
      - run:
          command: |2-

            KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
            eval "$(ssh-agent -s)"
            if [ -f "$KEYFILE" ]; then
              ssh-add "$KEYFILE"
            else
              echo "==> INFO: SSH key for github.com not found"
              echo "    Attempts to access private repositories from within"
              echo "    the build will fail, e.g. for private go modules, or"
              echo "    attempts to directly clone private repositories."
            fi

            make -f packages*.lock/layer.mk 05-ui-dependencies-03a9560cf6f4a4b3fbfbb962620287b558dbf506-image
          name: Build ui-dependencies layer
      - run:
          command: |2-

            KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
            eval "$(ssh-agent -s)"
            if [ -f "$KEYFILE" ]; then
              ssh-add "$KEYFILE"
            else
              echo "==> INFO: SSH key for github.com not found"
              echo "    Attempts to access private repositories from within"
              echo "    the build will fail, e.g. for private go modules, or"
              echo "    attempts to directly clone private repositories."
            fi

            make -f packages*.lock/layer.mk 06-build-ui-90fdcda527d1cfee8060beabb684c580d036ee74-image
          name: Build build-ui layer
      - run:
          command: |2-

            KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
            eval "$(ssh-agent -s)"
            if [ -f "$KEYFILE" ]; then
              ssh-add "$KEYFILE"
            else
              echo "==> INFO: SSH key for github.com not found"
              echo "    Attempts to access private repositories from within"
              echo "    the build will fail, e.g. for private go modules, or"
              echo "    attempts to directly clone private repositories."
            fi

            make -f packages*.lock/layer.mk 06-build-ui-90fdcda527d1cfee8060beabb684c580d036ee74-save
          name: Build build-ui layer
      - save_cache:
          paths:
            - .buildcache/archives/06-build-ui-90fdcda527d1cfee8060beabb684c580d036ee74.tar.gz
          key: build-ui_90fd_{{checksum ".buildcache/cache-keys/build-ui-90fdcda527d1cfee8060beabb684c580d036ee74"}}
          name: 'Save Layer Cache: build-ui'
  bundle-releases:
    executor: builder
    steps:
      - checkout:
          path: .
      - run:
          command: make -C packages*.lock write-all-package-cache-keys
          name: Write all package cache keys
      - run:
          command: mkdir -p .buildcache && echo "*" > .buildcache/.gitignore
          name: Ignore .buildcache
      - restore_cache:
          key: package-5f7076189296d55807a53aa53bfe785f73ec86f8-{{checksum ".buildcache/cache-keys/package-5f7076189296d55807a53aa53bfe785f73ec86f8"}}
          name: Restore package cache
      - run:
          command: make package-meta-all
          name: Write Package Metadata
      - run:
          command: make aliases
          name: Write package aliases
      - run:
          command: ls -lahR .buildcache
          name: List Build Cache
      - run:
          command: cp packages*.lock/pkgs.yml lockfile-33e6919abdc2300f4f3f712015a910d47c0c1f6d-9f966764665a4da8.yml
          name: Update Lockfile Name
      - run:
          command: tar -czf packages-33e6919abdc2300f4f3f712015a910d47c0c1f6d-9f966764665a4da8.tar.gz .buildcache/packages lockfile-33e6919abdc2300f4f3f712015a910d47c0c1f6d-9f966764665a4da8.yml
          name: Create Raw Package Tarball
      - run:
          command: tar -czf meta-33e6919abdc2300f4f3f712015a910d47c0c1f6d-9f966764665a4da8.tar.gz .buildcache/packages/store/*.json lockfile-33e6919abdc2300f4f3f712015a910d47c0c1f6d-9f966764665a4da8.yml
          name: Create Metadata Tarball
      - store_artifacts:
          path: lockfile-33e6919abdc2300f4f3f712015a910d47c0c1f6d-9f966764665a4da8.yml
      - store_artifacts:
          path: packages-33e6919abdc2300f4f3f712015a910d47c0c1f6d-9f966764665a4da8.tar.gz
      - store_artifacts:
          path: meta-33e6919abdc2300f4f3f712015a910d47c0c1f6d-9f966764665a4da8.tar.gz
      - run:
          command: mv ".buildcache/packages" "packages-33e6919abdc2300f4f3f712015a910d47c0c1f6d-9f966764665a4da8"
          name: Update Custom Build Paths
      - store_artifacts:
          path: packages-33e6919abdc2300f4f3f712015a910d47c0c1f6d-9f966764665a4da8
  darwin_amd64_package:
    executor: builder
    steps:
      - setup_remote_docker:
          version: 19.03.12
          docker_layer_caching: false
      - add_ssh_keys:
          fingerprints:
            - c6:96:98:82:dc:04:6c:39:dd:ac:83:05:e3:15:1c:98
      - checkout:
          path: .
      - run:
          command: make -C packages*.lock write-package-cache-key
          name: Write package cache key
      - restore_cache:
          key: package-5f7076189296d55807a53aa53bfe785f73ec86f8-{{checksum ".buildcache/cache-keys/package-5f7076189296d55807a53aa53bfe785f73ec86f8"}}
          name: Restore package cache
      - run:
          command: |2

            if ! { PKG=$(find .buildcache/packages/store -maxdepth 1 -mindepth 1 -name '*.zip' 2> /dev/null) && [ -n "$PKG" ]; }; then
              echo "No package found, continuing with build."
              exit 0
            fi
            echo "Package already cached, skipping build."
            circleci-agent step halt
          name: Check cache status
      - run:
          command: make -C packages*.lock write-builder-cache-keys
          name: Write builder layer cache keys
      - restore_cache:
          key: copy-source_d1e4_{{checksum ".buildcache/cache-keys/copy-source-d1e44780e7157229e756dd57c45172317faf7ea1"}}
          keys:
            - warm-go-build-vendor-cache_b1a4_{{checksum ".buildcache/cache-keys/warm-go-build-vendor-cache-b1a4f556a5d77f3dd79a814ad2c75d7f8df6552c"}}
            - build-static-assets_a099_{{checksum ".buildcache/cache-keys/build-static-assets-a0991d05a885188e95af8cbe5778accc12666279"}}
            - build-ui_90fd_{{checksum ".buildcache/cache-keys/build-ui-90fdcda527d1cfee8060beabb684c580d036ee74"}}
            - ui-dependencies_03a9_{{checksum ".buildcache/cache-keys/ui-dependencies-03a9560cf6f4a4b3fbfbb962620287b558dbf506"}}
            - install-yarn_4a71_{{checksum ".buildcache/cache-keys/install-yarn-4a71e9de991f85332680d0309a9fd3eef4d33a2c"}}
            - set-workdir_3f6f_{{checksum ".buildcache/cache-keys/set-workdir-3f6fd622b823df140b6d5bb7d1078de649239243"}}
            - install-go-tools_8ddd_{{checksum ".buildcache/cache-keys/install-go-tools-8dddb408568872d9ec907a8ba53068b13908ad64"}}
            - install-go_aada_{{checksum ".buildcache/cache-keys/install-go-aadaf7c6eb9ff4cceff9ba27d6e0253fb5bbec24"}}
            - base_c6cd_{{checksum ".buildcache/cache-keys/base-c6cdf1b224722d2520e082320f2a71875913247c"}}
          name: 'Restore Builder Image Cache: copy-source'
      - run:
          command: make -C packages*.lock load-builder-cache
          name: Load whatever builder cache we have (if any) into the Docker daemon
          no_output_timeout: 30m
      - run:
          command: |2-

            KEYFILE="$HOME/.ssh/id_rsa_c6969882dc046c39ddac8305e3151c98"
            eval "$(ssh-agent -s)"
            if [ -f "$KEYFILE" ]; then
              ssh-add "$KEYFILE"
            else
              echo "==> INFO: SSH key for github.com not found"
              echo "    Attempts to access private repositories from within"
              echo "    the build will fail, e.g. for private go modules, or"
              echo "    attempts to directly clone private repositories."
            fi

            make -C packages*.lock package
          name: Compile Package
      - run:
          command: ls -lahR .buildcache/packages
          name: List packages
      - save_cache:
          paths:
            - .buildcache/packages/store
          key: package-5f7076189296d55807a53aa53bfe785f73ec86f8-{{checksum ".buildcache/cache-keys/package-5f7076189296d55807a53aa53bfe785f73ec86f8"}}
          name: Save package cache
    environment:
      PACKAGE_SPEC_ID: 5f7076189296d55807a53aa53bfe785f73ec86f8
workflows:
  build-33e6919abdc2300f4f3f712015a910d47c0c1f6d-9f966764665a4da8:
    jobs:
      - build-common-layers: {}
      - darwin_amd64_package:
          requires:
            - build-common-layers
      - bundle-releases:
          requires:
            - darwin_amd64_package
